[package]
name = "InkBlob-notebook"
version = "1.0.0"
edition = "2024.beta"

[dependencies]
WAL = { local = "../vendor/wal" }

[addresses]
inkblob = "0x0"  # Will be updated after deployment
wal = "0x8270feb7375eee355e64fdb69c50abb6b5f9393a722883c1cf45f8e26048810a"

[dev-dependencies]
# Note: Sui Framework includes test utilities